### ISSUE TITLE
SyntaxError: Unexpected token =>

### ISSUE THREAD

**Issue by cklimkowsky** [wbkd/yet-another-webpack-es6-starterkit#1]
I'm trying to get up and running with this kit. I copied the contents of this repo into my own, and I'm running into the following errors after `npm install` and `npm run dev`:

```
/Users/cklimkow/workspace/js-lightbox/webpack.config-helper.js:3
const Path = require('path')
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/cklimkow/workspace/js-lightbox/webpack-dev.config.js:1:80)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```
This one is easy enough to fix, just remove `'use strict';` from webpack.config-helper.js

Then, I'm now running into this issue:
```
/Users/cklimkow/workspace/js-lightbox/webpack.config-helper.js:9
module.exports = (options) => {
                           ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/cklimkow/workspace/js-lightbox/webpack-dev.config.js:1:80)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```
But I don't have a quick solution to this one. I was hoping this kit would be a quick drag-and-drop solution. Help?

**Comment by moklick** [comment]
hey @cklimkowsky what node version are you using? Try to install the latest and it should work.

**Comment by cklimkowsky** [comment]
@moklick I was on the beautifully low version of 0.12.5 :sleepy: Thanks for the fast response!
