### ISSUE TITLE
missing string-width dependencies

### ISSUE THREAD

**Issue by ycrao** [wbkd/yet-another-webpack-es6-starterkit#13]
![image](https://user-images.githubusercontent.com/3280204/38715667-17e21f40-3f0f-11e8-9956-ba38ca2f82df.png)

When run `npm run dev` got errors !
```
> webpack-dev-server --open --config webpack-dev.config.js --watch --colors

module.js:471
    throw err;
    ^

Error: Cannot find module 'string-width'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (...)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! yet-another-webpack-es6-starterkit@1.0.0 dev: `webpack-dev-server --open --config webpack-dev.config.js --watch --colors`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the yet-another-webpack-es6-starterkit@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ....log
```

To fix this, need add  `"string-width": "^2.1.1"` dependencies to package.json file.

**Comment by g-div** [comment]
I think this was a problem of webpack-cli. It has been now solved.

Thanks!
